[package]
name = "BiMersenne"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
num-bigint = "0.4.6"
num-prime = "0.4.4"
num-integer = "0.1.46"
rayon = "1.10.0"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }